### ISSUE TITLE
richTextview再次进入图片不显示

### ISSUE THREAD

**Issue by zhihaozhang** [changdiqing/journal-Richtext-Editor-using-attributedString-#1]
您好，感谢您的代码，很不错，关于富文本编辑器部分有点困惑，好像添加的图片，后面再进入就无法看到了？请问是什么原因？期待您的回复，谢谢！

**Comment by changdiqing** [comment]
您好！这个repo 只是在下很久之前尝试的一个半成品。你遇到的问题应该是重新编译安装之后找不到图片？如果是这个情况的话是应为每次安装软件后对应的路径有所更改，这个旧的repo没有修复这个功能，软件还在按照之前的路径寻找图片。在我的另一个repo “RichtextEditor” 中这个问题已经修复了你可以试一下。

**Comment by zhihaozhang** [comment]
试用了一下，确实可以，谢谢。如果我想把富文本编辑器部分抽出来加入到我的项目，请问如何做呢？代价大么？~

**Comment by changdiqing** [comment]
还是比较麻烦的， 因为我的代码并没有把富文本编辑的部分很清楚的和其他模块区分开。我的富文本编辑器也是在一个pod 的基础上写的，你可以使用这个pod “RichEditorView”，它提供你基本的文本编辑和排版功能，之后你想附加其他的功能可以参考我的代码。基本上了解了 html css javascript， 然后了解一下联通swift层和javscript层的 库 ”javscriptcore“ 就可以上手了。 我觉得这个是最有效的方法。

**Comment by zhihaozhang** [comment]
嗯，谢谢您！
